export enum TIPO_OT {
  "SEDE",
  "RTS"
}

export enum ESTADOS_SEDE {
  "CREADA",
  "EQUIPO_ALMACENADO",
  "EQUIPO_EN_DIAGNOSTICO",
  "CONTROL_CALIDAD",
  "EQUIPO_ESTIBADO",
  "FINALIZADA"
}

export const ESTADOS_SEDE_NOMBRE: string[] = [
  "CREADA",
  "EQUIPO_ALMACENADO",
  "EQUIPO_EN_DIAGNOSTICO",
  "CONTROL_CALIDAD",
  "EQUIPO_ESTIBADO",
  "FINALIZADA"
];

export enum ESTADOS_RTS {
  "CREADA",
  "DIAGNOSTICO",
  "ESPERANDO_REPUESTOS",
  "REPARACION",
  "CONTROL_CALIDAD",
  "FINALIZADA"
}

export const ESTADOS_RTS_NOMBRE: string[] = [
  "CREADA",
  "DIAGNOSTICO",
  "ESPERANDO_REPUESTOS",
  "REPARACION",
  "CONTROL_CALIDAD",
  "FINALIZADA"
];
